#Le taux chaque jour est calculé à partir des 4 variables suivantes.
#Chaque quantité est injectée dans une fonction qui renvoi une valeur entre -1 et 1, puis sont additionnés selon des coefficients.
#Il est recommandé de changer les coefficients en cas de biais.
#La somme permet de définir les probabilités d'augmenter/diminuer le taux, ainsi que la durée d'évolution.
Taux:

  #La fonction variation est de la forme f(x) = { 2/(1+3^-x/M)-1 si x>0 , -2/(1+3^-x/m)+1 si x<0 }
  #m et M vérifient f(m) = -1/2 et f(M) = 1/2
  variation:
    m: -1000
    M: 5000

  #La fonction joueurs est de la forme f(x) = 1/a * ((1+a) / (1+a*(a+2)^-x/m) - 1 )
  #m vérifie f(m) = 1/2, a correspond à l'étalement de la logistique
  joueurs:
    m: 6
    a: 25

  #La fonction mort est de la forme f(x) = 2^-x/m - 1
  #m vérifie f(m) = 1/2
  mort:
    m: 5

  #La fonction diamonds est de la forme f(x) = 2^-x/m - 1
  #m vérifie f(m) = 1/2
  diamonds:
    m: 50

  #Après injection dans chaque fonction, chaque résultat est multiplié par un coefficient pour calculer la somme
  somme:
    aJoueurs: 0.5
    aVariation: 0.3
    aMort: 0.1
    aDiamonds: 0.1