#Le taux chaque jour est calculé à partir des 4 variables suivantes.
#Chaque quantité est injectée dans une fonction qui renvoi une valeur entre -1 et 1, puis sont additionnés selon des coefficients.
#Il est recommandé de changer les coefficients en cas de biais.
#La somme permet de définir les probabilités d'augmenter/diminuer le taux, ainsi que la durée d'évolution.
Taux:

  #La fonction variation est de la forme f(x) = { 2/(1+3^-x/M)-1 si x>0 , -2/(1+3^-x/m)+1 si x<0 }
  #m et M vérifient f(m) = -1/2 et f(M) = 1/2
  variation:
    m: -700
    M: 3500

  #La fonction joueurs est de la forme f(x) = 1/a * ((1+a) / (1+a*(a+2)^-x/m) - 1 )
  #m vérifie f(m) = 1/2, a correspond à l'étalement de la logistique
  joueurs:
    m: 5
    a: 25

  #La fonction mort est de la forme f(x) = 2^-x/m - 1
  #m vérifie f(m) = -1/2
  mort:
    m: 5

  #La fonction diamonds est de la forme f(x) = 2^-x/m - 1
  #m vérifie f(m) = -1/2
  diamonds:
    m: 30

  #Après injection dans chaque fonction, chaque résultat est multiplié par un coefficient pour calculer la somme
  Somme:
    aJoueurs: 0.5
    aVariation: 0.4
    aMort: 0.7
    aDiamonds: 0.3

  #Le taux suit toujours une évolution linéaire dont la pente est déterminée par la somme
  #La pente est donnée par f(x) = a / (1+a*exp(-rx)) - a/(a+1)
  Pente:
    a: 0.8
    r: 5

  #Le taux revient par défaut lentement vers sa valeur moyenne (5)
  #Ce retour est donné par f(x) = 1 / (1+exp(-r(x-5))) - 1/2
  Retour:
    r: -0.2
