name: stonkexchange
version: ${project.version}
main: fr.tim.stonkexchange.StonkExchange
api-version: 1.19

commands:
  baltop:
    description: Affiche les rangs de chaques joueurs
  bank:
    description: Permet de gérer le compte bancaire des joueurs
    usage: /bank <UUID/Name/Taux> [save]
    permission: admin
  group:
    description: Permet la gestion de groupes
    usage: /group <create/delete/modify/quit/list>
#  item:
#    permission: admin

permissions:
  admin:
    description: Commandes admin