name: stonkexchange
version: ${project.version}
main: fr.tim.stonkexchange.StonkExchange
api-version: 1.18

commands:
  baltop:
    description: Affiche les rangs de chaques joueurs
  bank:
    description: Permet de gérer le compte bancaire des joueurs
    usage: /bank <UUID/Name/Taux> [save]
    permission: admin
  vault:
    description: Fait appararaitre un coffre fort
    permission: admin

permissions:
  admin:
    description: Commandes admin