name: smpBank
version: ${project.version}
main: fr.tim.smpbank.StonksExchange
api-version: 1.18

commands:
  bank:
    description: Permet de gérer le compte bancaire des joueurs
    usage: /bank <UUID/Name/Taux> [save]
  vault:
    description: Fait appararaitre un coffre fort

permissions:
  admin:
    description: Commandes admin